#!/usr/bin/env bash

if [[ -s "/home/ubuntu/.rvm/environments/ruby-2.0.0-p247@global" ]]
then
  source "/home/ubuntu/.rvm/environments/ruby-2.0.0-p247@global"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/environments/ruby-2.0.0-p247@global'" >&2
  exit 1
fi
